# contrib/falcon/Makefile

PG_CFLAGS = -Wno-declaration-after-statement

MODULE_big = falcon
SUBDIRS = . metadb utils distributed_backend transaction control dir_path_shmem connection_pool plugin

falcon_srcdir = .
CXX_OBJS += \
	$(patsubst $(falcon_srcdir)/%.cpp,%.o,$(foreach dir,$(SUBDIRS), $(sort $(wildcard $(falcon_srcdir)/$(dir)/*.cpp))))
# Plugin sources are included in SUBDIRS above
OBJS += \
	$(patsubst $(falcon_srcdir)/%.c,%.o,$(foreach dir,$(SUBDIRS), $(sort $(wildcard $(falcon_srcdir)/$(dir)/*.c))))
OBJS += $(CXX_OBJS)

REMOTE_CONNECTION_DEF_DIR = $(falcon_srcdir)/../remote_connection_def
CONNECTION_POOL_DIR = $(falcon_srcdir)/connection_pool

FBS_DIR = $(shell find $(REMOTE_CONNECTION_DEF_DIR) -type d | grep -E '/fbs$$')
FBS_FILE = $(wildcard $(FBS_DIR)/*.fbs)
FBS_HEAD = $(patsubst $(REMOTE_CONNECTION_DEF_DIR)/%.fbs, $(CONNECTION_POOL_DIR)/%_generated.h, $(FBS_FILE))

all: $(FBS_HEAD) $(OBJS)

$(OBJS): $(FBS_HEAD)

$(CXX_OBJS): %.o: %.cpp
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -faligned-new -c $< -o $@

$(FBS_HEAD): $(FBS_FILE)
	mkdir -p $(CONNECTION_POOL_DIR)/fbs
	flatc --cpp -o $(CONNECTION_POOL_DIR)/fbs/ $(FBS_FILE)


PGFILEDESC = "falcon"

LDFLAGS_PROTO = -Wl,-Bdynamic -lprotobuf
LDFLAGS_DEPENDENCIES = -L../../../../falcon/third_party/glog/lib -lpthread -lgflags -lleveldb -lcrypto -lssl -ldl -lz -lglog

PG_CPPFLAGS = -Wno-deprecated-declarations -I$(libpq_srcdir) -I./include -I./connection_pool/proto -I./connection_pool/fbs \
			  -I$(REMOTE_CONNECTION_DEF_DIR) \
			  -I/usr/local/include \
			  -I$(falcon_srcdir)/../falcon/third_party/glog/include \
			  -I$(falcon_srcdir)/../third_party
SHLIB_LINK_INTERNAL =  -L../../src/interfaces/libpq -Wl,--no-as-needed -lpq -lstdc++ \
					-lz -Wl,--as-needed
ifneq ($(strip $(FALCONFS_INSTALL_DIR)),)
SHLIB_LINK_INTERNAL += -L$(FALCONFS_INSTALL_DIR)/lib -L$(FALCONFS_INSTALL_DIR)/lib64
endif
SHLIB_LINK_INTERNAL += $(LDFLAGS_PROTO) $(LDFLAGS_DEPENDENCIES)

EXTENSION = falcon
DATA = falcon--1.0.sql

ifdef USE_PGXS
PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)

# 覆盖 install 规则，安装到 FALCONFS 目录
ifdef FALCONFS_INSTALL_DIR
.PHONY: install-falconfs
install-falconfs: all
	$(MKDIR_P) '$(FALCONFS_INSTALL_DIR)/falcon_meta/lib/postgresql'
	$(MKDIR_P) '$(FALCONFS_INSTALL_DIR)/falcon_meta/share/extension'
	$(INSTALL_SHLIB) $(shlib) '$(FALCONFS_INSTALL_DIR)/falcon_meta/lib/postgresql/$(shlib)'
	$(INSTALL_DATA) $(EXTENSION).control '$(FALCONFS_INSTALL_DIR)/falcon_meta/share/extension/'
	$(INSTALL_DATA) $(DATA) '$(FALCONFS_INSTALL_DIR)/falcon_meta/share/extension/'
endif
else
subdir = contrib/falcon
top_builddir = ../..
include $(top_builddir)/src/Makefile.global
include $(top_srcdir)/contrib/contrib-global.mk
endif
